config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :books do
	collection do
		get 'search'
	end
	resources :reviews, except: [:show, :index]
	end
  root 'books#index'
	

end

app/models/book.rb
class Book < ActiveRecord::Base
	searchkick

	belongs_to :user
	has_many :reviews
	
	has_attached_file :image, styles: {medium: "400x600#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
has_many :books
has_many :reviews, dependent: :destroy
       end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :set_book, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]
# GET /books
# GET /books.json
def index
@books = Book.all
end

# GET /books/1
# GET /books/1.json

def search
	if params[:search].present?
		@books = Book.search(params[:search], limit:1000)
	else
		@books = Book.all
	end
	end
def show
@reviews = Review.where(book_id: @book.id).order("created_at DESC")
	@avg_review = @reviews.average(:rating)

end

# GET /books/new
def new
@book = current_user.books.build
end

# GET /books/1/edit
def edit
end

# POST /books
# POST /books.json
	def create
@book = current_user.books.build(book_params)

	respond_to do |format|
	if @book.save
	format.html { redirect_to @book, notice: 'Book was successfully created.' }
	format.json { render :show, status: :created, location: @book }
	else
	format.html { render :new }
	format.json { render json: @book.errors, status: :unprocessable_entity }
	end
	end
	end

# PATCH/PUT /books/1
# PATCH/PUT /books/1.json
	def update
	respond_to do |format|
if @book.update(book_params)
	format.html { redirect_to @book, notice: 'Book was successfully updated.' }
	format.json { render :show, status: :ok, location: @book }
	else
	format.html { render :edit }
	format.json { render json: @book.errors, status: :unprocessable_entity }
	end
	end
	end

# DELETE /books/1
# DELETE /books/1.json
	def destroy
	@book.destroy
	respond_to do |format|
	format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
	format.json { head :no_content }
	end
	end

	private
# Use callbacks to share common setup or constraints between actions.
	def set_book
@book = Book.find(params[:id])
	end

# Never trust parameters from the scary internet, only allow the white list through.
	def book_params
params.require(:book).permit(:title, :description, :length, :author, :style, :image)
	end
	end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_review, only: [:show, :edit, :update, :destroy]
before_action :set_book
before_action :authenticate_user!

	def index
	@reviews = Review.all
	end

	def show
	end


	def new
	@review = Review.new
	end


	def edit
	end

	def create
	@review = Review.new(review_params)
	@review.user_id = current_user.id
	@review.book_id = @book.id

	if @review.save
		redirect_to @book
	else
	render 'new'
	end
	end

	def update
	@review.update(review_params)
	end

	def destroy
	@review.destroy
	redirect_to root_path
	end

	private
	def set_review
	@review = Review.find(params[:id])
	end
	def set_book
	@book = Book.find(params[:book_id])
	end
# Never trust parameters from the scary internet, only allow the white list through.
	def review_params
params.require(:review).permit(:rating, :comment)
	end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { multipart: true } do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"><font color="white">
    <%= f.label :titre %><br>
	</font>
    <%= f.text_field :title %>
	
  </div>

  <div class="field"><font color="white">
    <%= f.label :description %><br>
	</font>
    <%= f.text_area :description %>  
  </div>

  <div class="field"><font color="white">
    <%= f.label :longueur %><br>
	</font>
    <%= f.text_field :length %>
	
  </div>

  <div class="field"><font color="white">
    <%= f.label :auteur %><br>
	</font>
    <%= f.text_field :author %>
	
  </div>

  <div class="field"><font color="white">
    <%= f.label :style %><br>
</font>
    <%= f.text_field :style %>
	
  </div>

  <div class="field">
	<font color="white">
	<%= f.label :image %><br>
	
	<%= f.file_field :image %>
	</font>

  <div class="actions">
    <%= f.submit %>

  </div>

<% end %>

app/views/books/edit.html.erb
<h1><font color="white">Editer un livre </font></h1>

<%= render 'form' %>

<%= link_to 'Voir', @book %> |
<%= link_to 'Retour', books_path %>

app/views/books/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
<h1>Noter les livres !</h1>
<p><%= link_to "Connectez vous pour noter un livre", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>
<% end %>

<div class="row">
<% @books.each do |book| %>
<div class="col-sm-6 col-md-3">
<div class="thumbnail">
<%= link_to (image_tag book.image.url(:medium), class: 'image'), book %>
</div>
</div>
<% end %>
</div>

app/views/books/new.html.erb
<h1><font color="white">Nouveau livre</font></h1>

<%= render 'form' %>

<%= link_to 'Retour', books_path %>

app/views/books/search.html.erb
<div class="row">
<% @books.each do |book| %>
<div class="col-sm-6 col-md-3">
<div class="tumbnail">
<%= link_to (image_tag book.image.url(:medium), class:'image'),book %>
</div>
</div>
<% end %>
</div>

app/views/books/show.html.erb
<div class="panel panel-default">
<div class="panel-body">
<div class="row">
<div class="col-md-4">
<%= image_tag @book.image.url(:medium) %>


<div class="star-rating" data-score= <%=@avg_review%></div>
	<em><%="#{@reviews.length} notes"%></em>

<div class="table-responsive">
<table class="table">
<tbody>
<tr>
<td><strong>Titre:</strong></td>
<td><%= @book.title %></td>
</tr>
<tr>
<td><strong>Description:</strong></td>
<td><%= @book.description %></td>
</tr>
<tr>
<td><strong>Logueur:</strong></td>
<td><%= @book.length%></td>
</tr>
<tr>
<td><strong>Auteur:</strong></td>
<td><%= @book.author %></td>
</tr>
<tr>
<td><strong>Style</strong></td>
<td><%= @book.style %></td>
</tr>
</tbody>
</table>
<%= link_to "Noter/Commenter", new_book_review_path(@book) %>
</div>
</div>
<div class="col-md-7.col-md-offeset-1">
<h1 class="review_title"><%= @book.title %></h1>
<p><%= @book.description %></p>
<% if@reviews.blank? %>
	<h3> Pas encore de notes/commentaires, voulez vous ajoutez le/la premier/première ?</h3>
	<%= link_to "Noter/Commenter", new_book_review_path(@book), class:"btn btn-danger" %>
	<% else %>
	<% @reviews.each do |review| %>
	<div class="reviews">
		<div class="star-rating" data-score= <%=review.rating %> ></div>
	
	<p><%= review.comment %></p>
	</div>
	<% end %>
	<% end %>
</div>
</div>
</div>
</div>
<%= link_to 'Editer', edit_book_path(@book) %> |
<%= link_to 'Retour', books_path %>

<script>
$('.star-rating').raty({
path: '/assets/',
readOnly: true,
score: function() {
return $(this).attr('data-score');
}
});
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container">

<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only"> Toggle navigation </span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "Accueil", root_path, class: "navbar-brand" %>
	</div>

	  <!--Collect the nav links,forms,and other content for toggling-->
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <ul class="nav navbar-nav">
	  <% if user_signed_in? %>
	  <li><%= link_to "Nouveau livre", new_book_path, class: "active" %></li>
	  <li><%= link_to "Compte", edit_user_registration_path %></li>
	  <% else %>
	  <li><%= link_to "S'enregistrer", new_user_registration_path, class: "active" %></li>
	  <li><%= link_to "Se connecter", new_user_session_path, class: "active" %></li>
	  <% end %>
	  </ul>
	<%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "rechercher" do%>
	<p>
	<%= text_field_tag :search, params[:search], class: "form-control"%>
	<%= submit_tag "Rechercher", name: nil, class: "btn btn-default"%>
	</p>
	<% end %>
	  
	  </div><!-- /.navbar-collapse-->
	  </div><!-- /.container-fluid-->
	  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Revue de livre</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container">
<%flash.each do |name, msg| %>
<% content_tag(:div, msg, class: "alert alert-info")%>
	<% end %>
	   <%= yield %>
		</div>
	   </body>
	   </html>

app/views/reviews/_form.html.erb
<%= form_for([@book,@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>

  <div class="field"><font color="white">
    <%= f.label :commentaire %><br>
	</font>
    <%= f.text_area :comment %>
	
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<script>
$('#star-rating').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
	});
</script>

app/views/reviews/edit.html.erb
<h1><font color="white">Editer<font></h1>

<%= render 'form' %>

<% link_to 'Voir', "#" %>
<%= link_to 'Retour', book_path(@book) %>

app/views/reviews/new.html.erb
<h1><font color="white">Nouvelle note</font></h1>

<%= render 'form' %>

<%= link_to 'Retour:', book_path(@book) %>